### PR TITLE
adjust comment format

### PR DESCRIPTION
**Pull request by aremazeilles**
FYI, I had to adjust the comment as suggested here to launch your code.

We aim at using linux machine to run the code. We run it from the terminal using these `run_pi_* ` file.
If possible, we will try to launch matlab code through octave. 
Are you developing under Matlab? Could you try your code under octave?

Then as you see in that file, the input parameter provide through the command line:

```term
./run_local_pi tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_run_0_platformData.csv tests/subject_2/protocol_1/subject_2_cond_1000000000/raw_data_input/subject_2_cond_1000000000_testbed.yaml output 1
```  

Are then transmitted to your main function:

```octave
Compute_Local_PI(filename, yaml_file, result_folder, isfall);
```

### CODE REVIEW

**Comment by aremazeilles** [comment]
Ping

**Comment by simomonte** [comment]
Hello Anthony, Sorry for the late reply.
For what concerns the launch code, there is no need to always write the whole file path for each file, as the code is capable to generate it for itself. 
I would suggest correcting the launch code as:
`./run_local_pi subject_2_cond_1000000000_run_0_platformData.csv subject_2_cond_1000000000_testbed.yaml subject_2/protocol_1'
that is transmitted in the same way to the main function.
For what concerns the use of Octave, we haven't tried yet to run our Matlab code with that, but I will do it in the next few days. 
Sorry again for the late reply.

**Comment by aremazeilles** [comment]
> I would suggest correcting the launch code as:
> `./run_local_pi subject_2_cond_1000000000_run_0_platformData.csv subject_2_cond_1000000000_testbed.yaml subject_2/protocol_1'

It is always a matter of from where is launched your code. The suggestion you make makes sense if you are located in the folder containing the data.

> there is no need to always write the whole file path for each file, as the code is capable to generate it for itself.

We do not want this behaviour for the entry point we will use. It requires making assumption on the pat, and each developer can make its own interpretation of what is better and what is not better. So this why we prefer setting explicitly the files this way.

The adjustment I propose is minor. Any issue with Merging this Pull Request?

**Comment by simomonte** [comment]
Oh ok, I understand your point of view. 
I think it is ok to merge the pull request. One question though. We adjust the code that generates the raw data so that it creates a folder structure and places the .csv and .yaml data in it. The folder structure is specific and is used to fasten the computation of the global PI. 
If you want to avoid this behavior with the assumption on the file path, does also that part of the code need to be changed?
In our mind, we aimed to have file folders well organized so that it is simpler for the operator to work with a huge amount of data.

**Comment by aremazeilles** [comment]
I think it is important to distinguish:

* the code used for collecting the data, through the different sensors etc... : this is used with the tesbed
* the code used to compute the metrics from the collected data: this will be launched through the eurobench server in our scheme.

The way you generate the data folder in the first stage is up to you (I assume your are referring to this, as you are talking about raw files). I would just suggest considering the proposed file naming pattern we mention in the [documentation](https://eurobench.github.io/sofware_documentation/latest/experiment_data.html). Indeed, as we want to make automatic the metric computation, we have to know which file refers to what. 

Then, regarding the metric computation, our code, the `PI manager`, will loop and call your program `run_pi`, for each of the runs that has been collected in a given experiment. We request all input files to be provided as I mentioned above. This way the filename is not important. And we request all result files (PI files, in yaml format) to be placed in a folder, which name should be  provided as last input parameter of the command (assuming the folder is already created).

**Comment by aremazeilles** [comment]
Could you accept this merge? Or do you see any problem with it?

**Pull request merged**
